name: Matrix Demo

on:
  push:
    branches:
        - main

jobs:
  buid:
    strategy:
      matrix: # allows yoy to run the same job using different configurations
        node-version: [16, 18, 20]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          path: node_modules
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build Project
        run: npm run build